Vdm\UserBundle\Entity\Utilisateur:
    type: entity
    table: null
    repositoryClass: Vdm\UserBundle\Repository\UtilisateurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
#    fields:
#        pseudo:
#            type: string
#            length: 255
#    lifecycleCallbacks: {  }
#
#    manyToOne:
#        image:
#            targetEntity: Vdm\VdmBundle\Entity\Image
#            cascade: ["persist", "remove"]

    manyToOne:
        message:
            targetEntity: Vdm\VdmBundle\Entity\Message
            inversedBy: utilisateurs
            joinColumn:
                name: utilisateur_id
                referencedColumnName: id