Vdm\VdmBundle\Entity\LikeMessage:
    type: entity
    table: null
    repositoryClass: Vdm\VdmBundle\Repository\LikeMessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }

    manyToOne:
        message:
            targetEntity: Vdm\VdmBundle\Entity\Message
    oneToOne:
        utilisateur:
          targetEntity: Vdm\UserBundle\Entity\Utilisateur
          joinColumn:
            name: utilisateur_id
            referencedColumnName: id
