<?php

namespace Vdm\VdmBundle\Repository;

/**
 * LikeMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
